version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: obs-overlay-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: obs_user
      POSTGRES_PASSWORD: obs_password
      POSTGRES_DB: obs_overlay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U obs_user -d obs_overlay']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
